import bcrypt from 'bcryptjs';

const data = {
    users:[
        {
        name:'Hammad',
        email: 'hammad.hm52@gmail.com',
        password: bcrypt.hashSync('123456',8),
        },
        {
        name:'Admin',
        email: 'admin@gmail.com',
        password: bcrypt.hashSync('123456',8),
        isAdmin:true,
        },
    ],
    products: [{
            _id: '1',
            name: 'Nike Slim Shirt 1',
            category: 'shirts',
            image: '/images/d1.jpg',
            price: 130,
            countInStock:10,
            brand: 'Nike',
            rating: 3,
            numReviews: 10,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '2',
            name: 'Nike Slim Shirt  2',
            category: 'shirts',
            image: '/images/d2.jpg',
            price: 220,
            countInStock:5,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 18,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt 3',
            category: 'shirts',
            image: '/images/d3.jpg',
            price: 5000,
            countInStock:50,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 30,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt 4',
            category: 'shirts',
            image: '/images/d1.jpg',
            price: 520,
            countInStock:0,
            brand: 'Nike',
            rating: 1.5,
            numReviews: 80,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '5',
            name: 'Nike Slim Shirt 5',
            category: 'shirts',
            image: '/images/d2.jpg',
            price: 320,
            countInStock:0,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt 6',
            category: 'pants',
            image: '/images/d3.jpg',
            price: 160,
            countInStock:90,
            brand: 'Nike',
            rating: 3,
            numReviews: 10,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '7',
            name: 'Nike Slim Shirt 7',
            category: 'pants',
            image: '/images/d1.jpg',
            price: 920,
            countInStock:52,
            brand: 'Nike',
            rating: 1,
            numReviews: 10,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '8',
            name: 'Nike Slim Shirt 8',
            category: 'pants',
            image: '/images/d3.jpg',
            price: 820,
            countInStock:18,
            brand: 'Nike',
            rating: .5,
            numReviews: 100,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '9',
            name: 'Nike Slim Shirt 9',
            category: 'pants',
            image: '/images/d2.jpg',
            price: 420,
            countInStock:11,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 5810,
            description: 'this is high quality product in the market now a days.',
        },
        {
            _id: '10',
            name: 'Nike Slim Shirt 10',
            category: 'pants',
            image: '/images/d3.jpg',
            price: 820,
            countInStock:45,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 122,
            description: 'this is high quality product in the market now a days.',
        },
    ],
};
export default data;